name: Bit.Hub Universal Compliance Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: bit-hub-compliance-${{ github.ref }}
  cancel-in-progress: false

jobs:
  compliance-wall:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    env:
      BITHUBREPOURL: https://github.com/Doctor0Evil/Bit.Hub.git
      POLICYDIR: .bithubpolicy
      REPORTDIR: .bithubreports

    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure audit/report directories exist
        run: |
          mkdir -p "$POLICYDIR" "$REPORTDIR"

      - name: Sync Bit.Hub Policy Modules
        run: |
          if git ls-remote "$BITHUBREPOURL" &>/dev/null; then
            git clone --depth=1 "$BITHUBREPOURL" tmpbithub
            rsync -av --ignore-existing tmpbithub/.bithubpolicy* "$POLICYDIR"/
            rm -rf tmpbithub
          else
            echo "::warning::Canonical Bit.Hub repo unreachable, using local policy"
          fi

      - name: Install OPA
        run: |
          curl -sL -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/opa

      - name: Audit Workflows + Code
        run: |
          if command -v opa >/dev/null; then
            opa eval --format pretty --data "$POLICYDIR" --input <(echo data) \
              || echo "::warning::OPA policy eval failed"
          else
            echo "::warning::OPA not installed/skipped"
          fi

      - name: Record Audit Log
        run: |
          echo "$(date -u) Compliance audit for Bit.Hub workflow run ${{ github.run_id }}" >> "$REPORTDIR/audit.log"
          touch "$REPORTDIR/${{ github.run_id }}.audit.json"

      - name: Upload Audit Log
        uses: actions/upload-artifact@v4
        with:
          name: bit-hub-compliance-audit
          path: .bithubreports
